#!/bin/bash -f

measure=$1
max_push_pop=$2
nb_threads=$3
non_blocking=$4

make WEIRD_NON_BLOCKING_DEF=1 MEASURE=$measure MAX_PUSH_POP=$max_push_pop NB_THREADS=$nb_threads NON_BLOCKING=$non_blocking SUFFIX=-$measure-$max_push_pop-$nb_threads-$non_blocking

